In [6]:
# add current directory to path
import sys
import os

sys.path.insert(0, os.getcwd())

In [7]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer

# Load the dataset
data = load_breast_cancer()

# Create a DataFrame
df_full = pd.DataFrame(data.data, columns=data.feature_names)

# Add the target variable to the DataFrame
df_full['target'] = data.target

# drop the highly correlated features
df_full = df_full.drop(
    labels=[
        "mean perimeter", "mean area", "perimeter error",
        "area error", "worst perimeter", "worst area"
	],
    axis=1
)

# drop mean fractal dimension (very low correlation)
df_full = df_full.drop(
    labels=[
        "mean fractal dimension"
	],
    axis=1
)
df_full

,mean radius,mean texture,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,radius error,texture error,smoothness error,...,fractal dimension error,worst radius,worst texture,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,0.11840,0.27760,0.30010,0.14710,0.2419,1.0950,0.9053,0.006399,...,0.006193,25.380,17.33,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,0.08474,0.07864,0.08690,0.07017,0.1812,0.5435,0.7339,0.005225,...,0.003532,24.990,23.41,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,0.10960,0.15990,0.19740,0.12790,0.2069,0.7456,0.7869,0.006150,...,0.004571,23.570,25.53,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,0.14250,0.28390,0.24140,0.10520,0.2597,0.4956,1.1560,0.009110,...,0.009208,14.910,26.50,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,0.10030,0.13280,0.19800,0.10430,0.1809,0.7572,0.7813,0.011490,...,0.005115,22.540,16.67,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,0.11100,0.11590,0.24390,0.13890,0.1726,1.1760,1.2560,0.010300,...,0.004239,25.450,26.40,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,0.09780,0.10340,0.14400,0.09791,0.1752,0.7655,2.4630,0.005769,...,0.002498,23.690,38.25,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,0.08455,0.10230,0.09251,0.05302,0.1590,0.4564,1.0750,0.005903,...,0.003892,18.980,34.12,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,0.11780,0.27700,0.35140,0.15200,0.2397,0.7260,1.5950,0.006522,...,0.006185,25.740,39.42,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,0.05263,0.04362,0.00000,0.00000,0.1587,0.3857,1.4280,0.007189,...,0.002783,9.456,30.37,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1

In [8]:
df = df_full.filter(regex="worst|target")
df

,worst radius,worst texture,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,25.380,17.33,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,24.990,23.41,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,23.570,25.53,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,14.910,26.50,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,22.540,16.67,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...
564,25.450,26.40,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,23.690,38.25,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,18.980,34.12,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,25.740,39.42,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,9.456,30.37,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1