In [50]:
import pandas as pd

df = pd.read_csv("./data/glass.csv")

# fixing data types
df['Type'] = df['Type'].astype('category')

# removing K and Ca columns (very low correlation)
df = df.drop(["K", "Ca"], axis=1)

In [51]:
df

          RI     Na    Mg    Al     Si    Ba   Fe Type
0    1.52101  13.64  4.49  1.10  71.78  0.00  0.0    1
1    1.51761  13.89  3.60  1.36  72.73  0.00  0.0    1
2    1.51618  13.53  3.55  1.54  72.99  0.00  0.0    1
3    1.51766  13.21  3.69  1.29  72.61  0.00  0.0    1
4    1.51742  13.27  3.62  1.24  73.08  0.00  0.0    1
..       ...    ...   ...   ...    ...   ...  ...  ...
209  1.51623  14.14  0.00  2.88  72.61  1.06  0.0    7
210  1.51685  14.92  0.00  1.99  73.06  1.59  0.0    7
211  1.52065  14.36  0.00  2.02  73.42  1.64  0.0    7
212  1.51651  14.38  0.00  1.94  73.61  1.57  0.0    7
213  1.51711  14.23  0.00  2.08  73.36  1.67  0.0    7

[214 rows x 8 columns]

In [52]:
df.describe()

,RI,Na,Mg,Al,Si,Ba,Fe
count,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000
mean,1.518365,13.407850,2.684533,1.444907,72.650935,0.175047,0.057009
std,0.003037,0.816604,1.442408,0.499270,0.774546,0.497219,0.097439
min,1.511150,10.730000,0.000000,0.290000,69.810000,0.000000,0.000000
25%,1.516522,12.907500,2.115000,1.190000,72.280000,0.000000,0.000000
50%,1.517680,13.300000,3.480000,1.360000,72.790000,0.000000,0.000000
75%,1.519157,13.825000,3.600000,1.630000,73.087500,0.000000,0.100000
max,1.533930,17.380000,4.490000,3.500000,75.410000,3.150000,0.510000

In [53]:
suspicious_values = [171, 172, 106, 163, 174, 175, 162, 161]

In [54]:
df.drop(labels=['Type'], axis=1).mean()

RI     1.518365
Na    13.407850
Mg     2.684533
Al     1.444907
Si    72.650935
Ba     0.175047
Fe     0.057009
dtype: float64

In [56]:
df[df['Type'] == 3].sort_values("Fe", ascending=False)

          RI     Na    Mg    Al     Si    Ba    Fe Type
162  1.52211  14.19  3.78  0.91  71.36  0.00  0.37    3
161  1.51934  13.64  3.54  0.75  72.65  0.15  0.24    3
150  1.51665  13.14  3.45  1.76  72.48  0.00  0.17    3
148  1.51670  13.24  3.57  1.38  72.70  0.00  0.10    3
159  1.51796  13.50  3.36  1.63  71.94  0.00  0.09    3
146  1.51769  13.65  3.66  1.11  72.77  0.00  0.00    3
151  1.52127  14.32  3.90  0.83  71.50  0.00  0.00    3
147  1.51610  13.33  3.53  1.34  72.67  0.00  0.00    3
149  1.51643  12.16  3.52  1.35  72.89  0.00  0.00    3
154  1.51694  12.86  3.58  1.31  72.61  0.00  0.00    3
153  1.51610  13.42  3.40  1.22  72.69  0.00  0.00    3
152  1.51779  13.64  3.65  0.65  73.00  0.00  0.00    3
155  1.51646  13.04  3.40  1.26  73.01  0.00  0.00    3
158  1.51776  13.53  3.41  1.52  72.04  0.00  0.00    3
157  1.52121  14.03  3.76  0.58  71.79  0.00  0.00    3
156  1.51655  13.41  3.39  1.28  72.64  0.00  0.00    3
160  1.51832  13.33  3.34  1.54  72.14  0.00  0.00    3